### PR TITLE
Last basic test is wrong

### PR DESCRIPTION
**Pull request by Philippe-Cholet**
Well it is a simple fix. An answer should be **-1** instead of **1**.

### CODE REVIEW

**Comment by cl0ne** [comment]
@Bryukh please take a look

**Comment by Bryukh** [comment]
@cl0ne you are right, this test was added after I left CheckiO and this is a wrong test. Not sure why was it accepted. Sadly I don't have control on this repository anymore. Maybe @oduvan can help here.

**Comment by oduvan** [comment]
Thank you for pointing out

**Comment by Bryukh** [comment]
Blame me. I checked the history and it was me who accepted that test. What's the shame

**Pull request merged**
